# =====================================================
# Layout configuration for the Home (About Me) page
#
# - The order of sections below determines their display order on the page.
# - Set `enabled: false` to hide a section from the page.
# - `variant` controls the style/layout of the section (if applicable).
# =====================================================

homepage:
  sections:
    - name: Introduction
      variant: default
      enabled: true

    - name: Experience
      variant: default
      enabled: true

    - name: Projects
      variant: default
      enabled: true

    - name: Skills
      variant: default
      enabled: true

    - name: Talks
      variant: default # default | card
      enabled: true

    - name: Services
      variant: default # default | card
      enabled: true
