# =====================================================
# Project data displayed on the Projects page.
#
# This section automatically fetches project information from your GitHub repositories.
#
# ✔ The `id` field should be the exact repository name
#    (e.g., from: github.com/<your-username>/<repo-name>)
#
# ✔ The `displayName` field controls how the project name appears on the website.
#
# ✔ Use the `featured` field to control which projects appear on the homepage.
#    - featured: true  → shown on the homepage
#    - featured: false → shown only on the Projects page
# =====================================================

projects:
  items:
    - id: "example-project" # name of your GitHub repository (from: github.com/<your-username>/<repo-name>)
      displayName: "[Project Name]" # name that will be displayed on the website
      previewImage: https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg
      featured: true

    - id: "Semi-Supervised-Regression"
      displayName: "Semi-Supervised Regression"
      previewImage: https://pm25.github.io/research-figures/rankup/figures/rankup-illustration.png
      featured: true

    - id: "SimplePlus-BeamerTheme"
      displayName: "SimplePlus Beamer Theme"
      previewImage: https://raw.githubusercontent.com/pm25/simpleplus-beamerTheme/master/preview/slide-1.webp
      featured: true

    - id: "SimpleDarkBlue-BeamerTheme"
      displayName: "SimpleDarkBlue Beamer Theme"
      previewImage: https://raw.githubusercontent.com/pm25/simpledarkblue-beamertheme/master/preview/slide-1.webp
      featured: true

    - id: "pm25.github.io"
      displayName: "pm25.github.io"
      previewImage: null
      featured: true

    - id: "flappy-bird"
      displayName: "Flappy Bird"
      previewImage: null
      featured: false
