# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "tashagrc"
  repoUrl: "https://github.com/tashagrc/natasharadika"
  description: "Natasha's Portfolio, iOS Engineer"
  author: "Natasha Radika"
