# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "natasharadika"
  repoUrl: "https://github.com/natasharadika/natasharadika"
  description: "A short description"
  author: "Your Name"
